/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:884494:
  appc.background(255);
} //_CODE_:window1:884494:

public void imgButton3_click1(GImageButton source, GEvent event) { //_CODE_:imgButton3:803002:
  println("imgButton3 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton3:803002:

public void slider2_change1(GSlider source, GEvent event) { //_CODE_:slider2:275304:
  heightMultiplier = slider2.getValueF();
} //_CODE_:slider2:275304:

public void redKnob_turn(GKnob source, GEvent event) { //_CODE_:redKnob:999691:
  red = redKnob.getValueF();
} //_CODE_:redKnob:999691:

public void greenKnob_turn(GKnob source, GEvent event) { //_CODE_:greenKnob:780043:
  green = greenKnob.getValueF();
} //_CODE_:greenKnob:780043:

public void blueKnob_turn(GKnob source, GEvent event) { //_CODE_:blueKnob:934557:
  blue = blueKnob.getValueF();
} //_CODE_:blueKnob:934557:

public void shapeSelector_click(GDropList source, GEvent event) { //_CODE_:shapeSelector:422049:
  String file = "s-" + shapeSelector.getSelectedText() + ".obj";
  println(file);
  //noLoop();
  loadNewShape(file);
} //_CODE_:shapeSelector:422049:

public void textureSelector_click(GDropList source, GEvent event) { //_CODE_:textureSelector:208989:
  img = loadImage("t-" + textureSelector.getSelectedText() + ".jpg");
  print("t-" + textureSelector.getSelectedText() + ".jpg");
} //_CODE_:textureSelector:208989:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "myGUI", 0, 0, 500, 500, JAVA2D);
  window1.noLoop();
  window1.addDrawHandler(this, "win_draw1");
  imgButton3 = new GImageButton(window1, 54, 18, 373, 98, new String[] { "title.jpg", "title.jpg", "title.jpg" } );
  imgButton3.addEventHandler(this, "imgButton3_click1");
  slider2 = new GSlider(window1, 19, 251, 167, 43, 10.0);
  slider2.setLimits(0.5, 0.0, 1.0);
  slider2.setNumberFormat(G4P.DECIMAL, 2);
  slider2.setOpaque(false);
  slider2.addEventHandler(this, "slider2_change1");
  redKnob = new GKnob(window1, 47, 407, 60, 60, 0.8);
  redKnob.setTurnRange(110, 70);
  redKnob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  redKnob.setSensitivity(1);
  redKnob.setShowArcOnly(false);
  redKnob.setOverArcOnly(false);
  redKnob.setIncludeOverBezel(false);
  redKnob.setShowTrack(true);
  redKnob.setLimits(255.0, 0.0, 255.0);
  redKnob.setShowTicks(true);
  redKnob.setOpaque(false);
  redKnob.addEventHandler(this, "redKnob_turn");
  greenKnob = new GKnob(window1, 206, 412, 60, 60, 0.8);
  greenKnob.setTurnRange(110, 70);
  greenKnob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  greenKnob.setSensitivity(1);
  greenKnob.setShowArcOnly(false);
  greenKnob.setOverArcOnly(false);
  greenKnob.setIncludeOverBezel(false);
  greenKnob.setShowTrack(true);
  greenKnob.setLimits(255.0, 0.0, 255.0);
  greenKnob.setShowTicks(true);
  greenKnob.setOpaque(false);
  greenKnob.addEventHandler(this, "greenKnob_turn");
  blueKnob = new GKnob(window1, 355, 414, 60, 60, 0.8);
  blueKnob.setTurnRange(110, 70);
  blueKnob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  blueKnob.setSensitivity(1);
  blueKnob.setShowArcOnly(false);
  blueKnob.setOverArcOnly(false);
  blueKnob.setIncludeOverBezel(false);
  blueKnob.setShowTrack(true);
  blueKnob.setLimits(255.0, 0.0, 255.0);
  blueKnob.setShowTicks(true);
  blueKnob.setOpaque(false);
  blueKnob.addEventHandler(this, "blueKnob_turn");
  label5 = new GLabel(window1, 22, 357, 108, 43);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Amount of red");
  label5.setOpaque(false);
  label6 = new GLabel(window1, 164, 354, 126, 45);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Amount of green");
  label6.setOpaque(false);
  label7 = new GLabel(window1, 332, 358, 111, 45);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Amount of blue");
  label7.setOpaque(false);
  shapeSelector = new GDropList(window1, 360, 191, 90, 80, 3);
  shapeSelector.setItems(loadStrings("list_422049"), 0);
  shapeSelector.addEventHandler(this, "shapeSelector_click");
  label8 = new GLabel(window1, 27, 172, 152, 67);
  label8.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label8.setText("Move the slider to change the height of the bars");
  label8.setOpaque(false);
  label9 = new GLabel(window1, 349, 151, 105, 33);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("Select your shape");
  label9.setOpaque(false);
  textureSelector = new GDropList(window1, 357, 267, 90, 80, 3);
  textureSelector.setItems(loadStrings("list_208989"), 0);
  textureSelector.addEventHandler(this, "textureSelector_click");
  label11 = new GLabel(window1, 341, 237, 126, 25);
  label11.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label11.setText("Select your texture");
  label11.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GImageButton imgButton3; 
GSlider slider2; 
GKnob redKnob; 
GKnob greenKnob; 
GKnob blueKnob; 
GLabel label5; 
GLabel label6; 
GLabel label7; 
GDropList shapeSelector; 
GLabel label8; 
GLabel label9; 
GDropList textureSelector; 
GLabel label11; 
